db:
  image: mongo:3.5.5
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat:0.54.2
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://192.168.99.100/
    - Accounts_UseDNSDomainCheck=True
    - ADMIN_USERNAME=admin
    - ADMIN_PASS=supersecret
    - ADMIN_EMAIL=admin@example.com
  links:
    - db:db
  ports:
    - 3000:3000

hubot:
  image: rocketchat/hubot-rocketchat:v1.0.6
  environment:
    - ROCKETCHAT_URL=192.168.99.100:3000
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=bot
    - LISTEN_ON_ALL_PUBLIC=true
    - BOT_NAME=hubot
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings,hubot-diagnostics,hubot-google,hubot-reddit,hubot-bofh,hubot-bookmark,hubot-shipit,hubot-maps
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080
