---
# PVC 1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim0
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-silver"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# PVC 2
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim1
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-silver"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
