---
# PVC 1
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: db-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
# PVC 2
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: db-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
