apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: db
    spec:
      containers:
      - args:
        - mongod
        - --smallfiles
        image: mongo:3.5.5
        name: db
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: db-claim0
        - mountPath: /dump
          name: db-claim1
      restartPolicy: Always
      volumes:
      - name: db-claim0
        persistentVolumeClaim:
          claimName: db-claim0
      - name: db-claim1
        persistentVolumeClaim:
          claimName: db-claim1
status: {}
