apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: rocketchat
  name: rocketchat
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: rocketchat
status:
  loadBalancer: {}
