apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: hubot
  name: hubot
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 8080
  selector:
    service: hubot
status:
  loadBalancer: {}
